### ISSUE TITLE
What does the index returned by mphf::lookup() mean?

### ISSUE THREAD

**Issue by 607011** [rizkg/BooPHF#17]
Looking at the [example code](https://github.com/rizkg/BBHash/blob/88fba4e50149d2d05855df0994f668b0f82783f7/example_custom_hash_strings.cpp#L123) you might think that `bhpf->lookup()` returns an index that can be used to access the element in the original data. If that were so, code like

```
for (u_int64_t i = 0; i < nelem; i++){
  uint64_t idx = bphf->lookup(data[i]);
  assert(data[idx] == data[i]);
}
```

would never fail. But it does – on every element.

So, what exactly does the index returned by `mphf::lookup()` mean?

**Comment by rchikhi** [comment]
Hi, 
Indeed, this is a minimal perfect hash function, not a monotone minimal perfect hash function. `lookup()` returns an index (`idx`) for `data[i]` which has no reason to be equal to `i`. The returned index has no meaning by itself. Keep in mind that the MPHF has allowed you to construct an exact association between each of the elements in `data` and the interval of integers `[0..len(data)]`, which is a non-trivial task in most cases. It's up to you to make use of that association, e.g. to build a dictionary.

**Comment by peekxc** [comment]
Just to add some context, as this confused me originally: 

As @rchikhi mentioned, the only requirement of a MPHF is to map a fixed set to {0, ..., n-1}; a MPHF that does this while e.g. preserving the order of the keys is called _order preserving_ (see https://cmph.sourceforge.net/), though in general this is quite a large property to ask out of MPHF. 

Also note that while you _can_ build a dictionary by e.g. building an array of offsets, said dict won't have the nice "uses c bits / key" property that most MPHF's have. There is the DAG-based [CHM hashing approach](https://cmph.sourceforge.net/chm.html), which is order-preserving, but in my experience it can be difficult to construct, and you still need to allocate an auxiliary array that is some multiplier $c \geq 2$ larger than the size of the array that just stores the keys themselves! 

There is also a simple way to construct an order-preserving MPHF that uses an offset array via linear programming, but this is not competitive with any of the existing algorithms and is only scalable for small key sets (but it easy to program!)
